name: Run Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Run Tests
        run: |
          npm ci
          npm test